name: Run Final Script Every Weekday

on:
  schedule:
    - cron: "30 11 * * 1-5"  # Runs at 11:30 AM UTC, which is 5:00 PM IST (UTC+5:30)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python Final_Script.py

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
         # Configure Git
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"

         # Authenticate using PAT
         git remote set-url origin https://x-access-token:${PAT}@github.com/pratmo/tradingtrendz.git

         # Add all changed files (HTML & CSV)
         git add -A

         # Commit if there are changes
         git diff --staged --quiet || git commit -m "Auto-update HTML and CSV files"

         # Push changes
         git push origin main

